[package]
name = "radroots-nostr"
version.workspace = true
edition.workspace = true
authors = ["triesap npub1tr33s4tj2le2kk9yzhfphdtss26gyn8kv7savnnjhj794nqp333q8e7grr"]
rust-version.workspace = true
license.workspace = true

[features]
default = ["std", "sdk"]
std = []
sdk = ["dep:nostr-sdk"]
codec = ["dep:radroots-events", "dep:radroots-events-codec"]
events = ["dep:radroots-events"]
http = ["dep:reqwest"]

[dependencies]
radroots-events = { workspace = true, optional = true, default-features = false }
radroots-events-codec = { workspace = true, optional = true, default-features = false }
nostr = { workspace = true, features = ["nip04"] }
nostr-sdk = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true, default-features = false, features = ["json", "rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
