[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"
license = "AGPL-3.0"

[workspace.dependencies]
radroots-core = { path = "crates/core", version = "0.1.0", default-features = false }
radroots-events = { path = "crates/events", version = "0.1.0", default-features = false }
radroots-events-codec = { path = "crates/events-codec", version = "0.1.0", default-features = false }
radroots-trade = { path = "crates/trade", version = "0.1.0", default-features = false }

anyhow = { version = "1" }
clap = { version = "4" }
config = { version = "0.14" }
nostr = { version = "0.43.0" }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
rust_decimal = { version = "1", default-features = false }
rust_decimal_macros = { version = "1" }
tempfile = { version = "3" }
thiserror = { version = "1" }
tokio = { version = "1" }
toml = { version = "0.8" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
tracing-appender = { version = "0.2" }
typeshare = { version = "1" }
