[package]
name = "radroots-sql-wasm-core"
version.workspace = true
edition.workspace = true
authors = ["triesap npub1tr33s4tj2le2kk9yzhfphdtss26gyn8kv7savnnjhj794nqp333q8e7grr"]
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["bridge"]
bridge = ["dep:radroots-sql-wasm-bridge"]
embedded = ["dep:rusqlite", "radroots-sql-core/native"]

[dependencies]
radroots-sql-core = { workspace = true }
radroots-sql-wasm-bridge = { workspace = true, optional = true }
rusqlite = { workspace = true, features = ["bundled", "serialize"], optional = true }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
ts-rs = { workspace = true }
uuid = { workspace = true, features = ["v4", "fast-rng", "js"] }
