[package]
name = "radroots-nostr-ndb"
version.workspace = true
edition.workspace = true
authors = ["triesap npub1tr33s4tj2le2kk9yzhfphdtss26gyn8kv7savnnjhj794nqp333q8e7grr"]
rust-version.workspace = true
license.workspace = true

[features]
default = ["std", "rt", "ndb", "runtime-adapter"]
std = []
rt = ["std", "dep:futures", "dep:tokio"]
ndb = ["std", "dep:nostrdb"]
runtime-adapter = ["std", "dep:radroots-nostr-runtime"]
giftwrap = ["std", "ndb"]

[dependencies]
radroots-nostr = { workspace = true, default-features = false, features = ["std"] }
radroots-nostr-runtime = { workspace = true, optional = true, default-features = false, features = ["std", "rt", "nostr-client"] }
futures = { workspace = true, optional = true }
hex = { workspace = true }
nostrdb = { version = "0.9.0", optional = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true, features = ["rt", "sync", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tempfile = { workspace = true }
