[package]
name = "radroots-tangle-events"
version.workspace = true
edition.workspace = true
authors = ["triesap npub1tr33s4tj2le2kk9yzhfphdtss26gyn8kv7savnnjhj794nqp333q8e7grr"]
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = ["std"]
std = [
    "radroots-events/std",
    "radroots-events-codec/std",
    "dep:base64",
    "dep:uuid",
]

[dependencies]
radroots-events = { workspace = true, default-features = false, features = ["serde"] }
radroots-events-codec = { workspace = true, default-features = false, features = ["serde_json"] }
radroots-sql-core = { workspace = true }
radroots-tangle-db-schema = { workspace = true }
radroots-tangle-db = { workspace = true }
radroots-types = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, default-features = false, features = ["alloc", "derive"] }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
sha2 = { workspace = true, default-features = false }
base64 = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[dev-dependencies]
radroots-sql-core = { workspace = true, features = ["native"] }
radroots-tangle-db = { workspace = true }
serde_json = { workspace = true }
